# Generated by Django 5.0.1 on 2024-02-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
    ]
